# Generated by Django 4.1.3 on 2022-11-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company/%y/%m/%d/')),
                ('call_us', models.CharField(max_length=100)),
                ('email_us', models.EmailField(max_length=100)),
                ('subtitle', models.TextField(max_length=500)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('emails', models.TextField(max_length=100)),
                ('numbers', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
